apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 discovery-server 8761; do echo waiting for discovery-server; sleep 2; done;"
      containers:
        - name: admin-server
          image: anwirisme/spring-petclinic-admin-server:main
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
            - name: SPRING_APPLICATION_NAME
              value: admin-server
            - name: SPRING_APPLICATION_INSTANCE_ID
              value: admin-server:${HOSTNAME}
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: EUREKA_INSTANCE_HOSTNAME
              value: admin-server
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  type: NodePort
