apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w30 discovery-server 8761; do echo waiting for discovery-server; sleep 2; done;"
      containers:
        - name: visits-service
          image: anwirisme/spring-petclinic-visits-service:main
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
            - name: SPRING_ZIPKIN_TRACING_ENDPOINT
              value: http://tracing-server:9411/api/v2/spans
            - name: SPRING_APPLICATION_NAME
              value: visits-service
            - name: SPRING_APPLICATION_INSTANCE_ID
              value: ${spring.application.name}:${random.uuid}
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: EUREKA_INSTANCE_HOSTNAME
              value: visits-service
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  selector:
    app: visits-service
  ports:
    - port: 8082
      targetPort: 8082
